### ISSUE TITLE
some bugs find in v0.8.0

### ISSUE THREAD

**Issue by lengyjc** [nacos-group/nacos-sdk-csharp#48]
1.There is a null object error found in AddNacosConfiguration method when i use Action part 
2. I found the listener request frequency is to high when add muti dataId 
3.I found the login request frequency will much high when the nacos server is down 

And the nacos server will go down in  the scene  that i start 200 program which has read config all the time and inject about 7 DataId

**Comment by lengyjc** [comment]
the first problem fixed when i add this code 
![image](https://user-images.githubusercontent.com/7983361/97127909-e4abaa00-1775-11eb-8db5-b767da473180.png)

**Comment by catcherwong** [comment]
@lengyjc Thanks for your interest in this project.

We will take a look ASAP for the last two problems.

The PR I have merged. You can take a look on the last preview version.

**Comment by lengyjc** [comment]
@catcherwong  Is the last  two problems fixed? If not, could i ask how long will it take.

**Comment by catcherwong** [comment]
> 3.I found the login request frequency will much high when the nacos server is down

There is a timer will try to do login per 5 second, if the nacos server is up, calling login request, it will tell us the ttl and refresh window of the access_token.

We will do login request based on ttl, refresh window and the last refresh time(succeed request time).

https://github.com/nacos-group/nacos-sdk-csharp/blob/e2b047ab27b93cf39d2c9c20ae16fccbadc88daf/src/Nacos/Security/SecurityProxy.cs#L52-L76

When the nacos server is down, the last refresh time will not be changed due to all requests are failed. So it will do request every 5 second.

**Comment by catcherwong** [comment]
> 2. I found the listener request frequency is to high when add muti dataId

At this time, a `dataId` and `group` will create a timer to pull the configuration. and the `ListenInterval` is 20000ms.
