### ISSUE TITLE
INacosServerManager can not retrieve available services

### ISSUE THREAD

**Issue by kookpua** [nacos-group/nacos-sdk-csharp#6]
用 https://github.com/nacos-group/nacos-sdk-csharp/tree/master/samples 的APP1和APP2跑起来，能够注册服务到nacos，但是发现不了服务，如下代码：

```c#

_serverManager.GetServerAsync("App1").GetAwaiter().GetResult();

```

看了下一下代码没有获取到weight，加上weight就可以获取到服务了，请教下，不改源代码怎么能够发现服务？

```c#
                    var list = serviceInstances.Hosts.Select(x => new NacosServer
                    {

                        // it seems that nacos don't return the scheme

                        // so here use http only.

                        Url = $"http://{x.Ip}:{x.Port}",

                        //加上这个就可以发现服务了

                        Weight=x.Weight

                    }).ToList();
```

**Comment by catcherwong** [comment]
@kookpua   谢谢您对这个项目感兴趣！

`INacosServerManager` 是基于接口的，可以自己实现对应的方法，然后在DI那里做对应的替换就可以了。

出现这个问题是调整了获取可用服务的算法，无权重->带权重，但是没有把权重字段赋值。

-------

Thanks for your interest in this project.

`INacosServerManager` is based on interface, you can implement it by yourself, the replace it in dependency injection.

The problem is that the algorithm for obtaining available services has been adjusted, from without weight to with weight, and the weight field is not assigned.

**Comment by kookpua** [comment]
> @kookpua 谢谢您对这个项目感兴趣！
> 
> `INacosServerManager` 是基于接口的，可以自己实现对应的方法，然后在DI那里做对应的替换就可以了。
> 
> 出现这个问题是调整了获取可用服务的算法，无权重->带权重，但是没有把权重字段赋值。
> 
> 如果您有时间的话，可以提个PR过来修复这个问题。 😄
> 
> Thanks for your interest in this project.
> 
> `INacosServerManager` is based on interface, you can implement it by yourself, the replace it in dependency injection.
> 
> The problem is that the algorithm for obtaining available services has been adjusted, from without weight to with weight, and the weight field is not assigned.
> 
> If you have time, you can send a PR to fix this problem. 😄

Thank you for your explanation, I will give it a try, I will have time next week
